[mypy]
python_version = 3.9
files = research/backtester_v3a
exclude = ^research/backtester_v3a/tests/
explicit_package_bases = True
strict = True
warn_unused_ignores = True
warn_unreachable = True
show_error_codes = True
pretty = True

[mypy-research.backtester_v2.*]
follow_imports = skip
ignore_missing_imports = True
