from __future__ import annotations

FEATURE_DICTIONARY_ROWS = [
    {
        "feature_name": "atr14_sma",
        "table_name": "market_features_rolling_4h_causal.parquet",
        "description": "Simple moving average ATR over the previous 14 true ranges.",
        "exact_formula": "mean(true_range[t-14:t-1])",
        "formula_status": "exact",
        "timeframe": "4h",
        "window": "14",
        "units": "price",
        "signed_or_absolute": "absolute",
        "available_at_time_rule": "available at current open after previous 14 closes",
        "is_causal": True,
        "uses_future_leg_direction": False,
        "uses_future_leg_boundary": False,
        "uses_future_parent": False,
        "uses_future_reference": False,
        "missing_value_rule": "NaN before 14 prior bars",
        "notes": "",
    },
    {
        "feature_name": "close_path_efficiency_4h",
        "table_name": "market_features_rolling_4h_causal.parquet",
        "description": "Directional efficiency of the prior close path.",
        "exact_formula": "abs(last_close-first_close)/sum(abs(diff(close)))",
        "formula_status": "exact",
        "timeframe": "4h",
        "window": "18|42|84",
        "units": "ratio",
        "signed_or_absolute": "absolute",
        "available_at_time_rule": "available at current open using prior closed bars only",
        "is_causal": True,
        "uses_future_leg_direction": False,
        "uses_future_leg_boundary": False,
        "uses_future_parent": False,
        "uses_future_reference": False,
        "missing_value_rule": "NaN when path length is zero or history too short",
        "notes": "",
    },
]
